exit from 'download-toolchain' script when URL is empty
git-svn-id: https://svn.radix.pro/svn/build-system/branches/BS-external@29 a865b717-3f32-42de-8836-d5b8ef941a95

diff --git a/download-toolchain b/download-toolchain
--- a/download-toolchain
+++ b/download-toolchain
@@ -4,6 +4,13 @@ trap 'echo ""; echo "`basename $0`: interrupted"; killall wget && killall "`base
 
 TARBALL=$1
 
+if [ -z "$TARBALL" ] ; then
+  echo "#"
+  shtool echo -e "# %BERROR%b: Toolchain URL is not defined."
+  echo "#"
+  exit 1
+fi
+
 tarball=`basename $TARBALL`
 
 progress() {
